// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDCLIPPER__
#define __AUTO_CODE_SUPERPOWEREDCLIPPER__

#ifdef __cplusplus
extern "C" {
#endif

extern void * SuperpoweredClipper_new();
extern void SuperpoweredClipper_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredClipper_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif