// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDRESAMPLER__
#define __AUTO_CODE_SUPERPOWEREDRESAMPLER__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredResampler_reset(void * class_handler);
extern void * SuperpoweredResampler_new();
extern int SuperpoweredResampler_process(void * class_handler,short* input, float* temp, short* output, int numberOfSamples, bool reverse, bool highQuality, float rateAdd);
extern int SuperpoweredResampler_process(void * class_handler,short* input, float* output, int numberOfSamples, bool reverse, bool highQuality, float rateAdd);
extern void SuperpoweredResampler_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif