// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDTIMESTRETCHING__
#define __AUTO_CODE_SUPERPOWEREDTIMESTRETCHING__

#ifdef __cplusplus
extern "C" {
#endif

extern int SuperpoweredTimeStretching_setRateAndPitchShiftCents(void * class_handler,float newRate, int newShiftCents);
extern void SuperpoweredTimeStretching_reset(void * class_handler);
extern void * SuperpoweredTimeStretching_new(unsigned int samplerate, float minimumRate, unsigned char sound);
extern void SuperpoweredTimeStretching_process(void * class_handler,SuperpoweredAudiobufferlistElement* input, SuperpoweredAudiopointerList* outputList);
extern void SuperpoweredTimeStretching_delete(void * class_handler);
extern void SuperpoweredTimeStretching_removeSamplesFromInputBuffersEnd(void * class_handler,unsigned int samples);
extern void SuperpoweredTimeStretching_setStereoPairs(void * class_handler,unsigned int numStereoPairs);
extern int SuperpoweredTimeStretching_setRateAndPitchShift(void * class_handler,float newRate, int newShift);
extern void SuperpoweredTimeStretching_setSampleRate(void * class_handler,unsigned int samplerate);

#ifdef __cplusplus
}
#endif

#endif