// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDMIXER__
#define __AUTO_CODE_SUPERPOWEREDMIXER__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredStereoMixer_processPFL(void * class_handler,float** channels, float** outputs, bool* channelSwitches[4], float* channelOutputLevels[4], unsigned int numberOfSamples);
extern void SuperpoweredStereoMixer_process(void * class_handler,float** inputs, float** outputs, float* inputLevels[8], float* outputLevels[2], float* inputMeters[8], float* outputMeters[2], unsigned int numberOfSamples);
extern void * SuperpoweredStereoMixer_new();
extern void SuperpoweredStereoMixer_delete(void * class_handler);

extern void SuperpoweredMonoMixer_delete(void * class_handler);
extern void SuperpoweredMonoMixer_process(void * class_handler,float** inputs, void* output, float* inputLevels, float outputGain, unsigned int numberOfSamples);
extern void * SuperpoweredMonoMixer_new();

#ifdef __cplusplus
}
#endif

#endif