// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDDELAY__
#define __AUTO_CODE_SUPERPOWEREDDELAY__

#ifdef __cplusplus
extern "C" {
#endif

extern void * SuperpoweredDelay_new(unsigned int maximumDelayMs, unsigned int maximumSamplerate, unsigned int maximumNumberOfFramesToProcess, unsigned int samplerate);
extern const float * const SuperpoweredDelay_process(void * class_handler,float* input, int numberOfFrames, SuperpoweredFX* fx);
extern void SuperpoweredDelay_reset(void * class_handler);
extern void SuperpoweredDelay_delete(void * class_handler);
extern void SuperpoweredDelay_setSamplerate(void * class_handler,unsigned int samplerate);

#ifdef __cplusplus
}
#endif

#endif