// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDCOMPRESSOR__
#define __AUTO_CODE_SUPERPOWEREDCOMPRESSOR__

#ifdef __cplusplus
extern "C" {
#endif

extern int SuperpoweredCompressor_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredCompressor_delete(void * class_handler);
extern void SuperpoweredCompressor_enable(void * class_handler,bool flag);
extern void SuperpoweredCompressor_setSamplerate(void * class_handler,unsigned int samplerate);
extern void * SuperpoweredCompressor_new(unsigned int samplerate);
extern float SuperpoweredCompressor_getGainReductionDb(void * class_handler);
extern void SuperpoweredCompressor_reset(void * class_handler);

extern void SuperpoweredCompressorProto_setSamplerate(void * class_handler,unsigned int samplerate);
extern void * SuperpoweredCompressorProto_new(unsigned int samplerate);
extern int SuperpoweredCompressorProto_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredCompressorProto_reset(void * class_handler);
extern float SuperpoweredCompressorProto_getGainReductionDb(void * class_handler);
extern void SuperpoweredCompressorProto_enable(void * class_handler,bool flag);
extern int SuperpoweredCompressorProto_process(void * class_handler,float* input, float* sidechain, float* output, unsigned int numberOfSamples);
extern void SuperpoweredCompressorProto_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif