// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDSPATIALIZER__
#define __AUTO_CODE_SUPERPOWEREDSPATIALIZER__

#ifdef __cplusplus
extern "C" {
#endif

extern void * SuperpoweredSpatializer_new(unsigned int samplerate);
extern void SuperpoweredSpatializer_delete(void * class_handler);
extern void SuperpoweredSpatializer_setSamplerate(void * class_handler,unsigned int samplerate);
extern int SuperpoweredSpatializer_process(void * class_handler,float* inputLeft, float* inputRight, float* outputLeft, float* outputRight, unsigned int numberOfSamples, bool outputAdd);

extern int SuperpoweredSpatializerGlobalReverb_process(float* output, unsigned int numberOfSamples);
extern void SuperpoweredSpatializerGlobalReverb_delete(void * class_handler);
extern void SuperpoweredSpatializerGlobalReverb_setReverbSamplerate(unsigned int samplerate);
extern void * SuperpoweredSpatializerGlobalReverb_new();

#ifdef __cplusplus
}
#endif

#endif