// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDRECORDER__
#define __AUTO_CODE_SUPERPOWEREDRECORDER__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredRecorder_delete(void * class_handler);
extern int SuperpoweredRecorder_start(void * class_handler,char const* destinationPath);
extern void * SuperpoweredRecorder_new(char const* tempPath, unsigned int samplerate, unsigned int minSeconds, unsigned char numChannels, bool applyFade,void * callback,void * clientData);
extern void SuperpoweredRecorder_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredRecorder_addToTracklist(void * class_handler,char* artist, char* title, int offsetSeconds, bool takeOwnership);
extern void SuperpoweredRecorder_stop(void * class_handler);
extern unsigned int SuperpoweredRecorder_process(void * class_handler,float* input, unsigned int numberOfSamples);
extern unsigned int SuperpoweredRecorder_process(void * class_handler,float* input0, float* input1, unsigned int numberOfSamples);

#ifdef __cplusplus
}
#endif

#endif