// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDROLL__
#define __AUTO_CODE_SUPERPOWEREDROLL__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredRoll_reset(void * class_handler);
extern void SuperpoweredRoll_setSamplerate(void * class_handler,unsigned int samplerate);
extern void * SuperpoweredRoll_new(unsigned int samplerate);
extern void SuperpoweredRoll_delete(void * class_handler);
extern int SuperpoweredRoll_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredRoll_enable(void * class_handler,bool flag);

#ifdef __cplusplus
}
#endif

#endif