// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDFREQUENCYDOMAIN__
#define __AUTO_CODE_SUPERPOWEREDFREQUENCYDOMAIN__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredFrequencyDomain_addInput(void * class_handler,SuperpoweredAudiobufferlistElement* input);
extern int SuperpoweredFrequencyDomain_timeDomainToFrequencyDomain(void * class_handler,float* magnitude, float* phase, float valueOfPi, bool complexMode);
extern void SuperpoweredFrequencyDomain_addInput(void * class_handler,float* input, int numberOfSamples);
extern void SuperpoweredFrequencyDomain_advance(void * class_handler,int numberOfSamples);
extern void SuperpoweredFrequencyDomain_setStereoPairs(void * class_handler,unsigned int numStereoPairs);
extern int SuperpoweredFrequencyDomain_timeDomainToFrequencyDomain(void * class_handler,float* magnitudeL, float* magnitudeR, float* phaseL, float* phaseR, float valueOfPi, bool complexMode, int stereoPairIndex);
extern void SuperpoweredFrequencyDomain_delete(void * class_handler);
extern void SuperpoweredFrequencyDomain_frequencyDomainToTimeDomain(void * class_handler,float* magnitudeL, float* magnitudeR, float* phaseL, float* phaseR, float* output, float valueOfPi, int incrementSamples, bool complexMode, int stereoPairIndex);
extern void SuperpoweredFrequencyDomain_reset(void * class_handler);
extern void * SuperpoweredFrequencyDomain_new(int fftLogSize, int maxOverlap);

#ifdef __cplusplus
}
#endif

#endif