// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDLIMITER__
#define __AUTO_CODE_SUPERPOWEREDLIMITER__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredLimiter_enable(void * class_handler,bool flag);
extern void SuperpoweredLimiter_reset(void * class_handler);
extern int SuperpoweredLimiter_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void * SuperpoweredLimiter_new(unsigned int samplerate);
extern void SuperpoweredLimiter_setSamplerate(void * class_handler,unsigned int samplerate);
extern float SuperpoweredLimiter_getGainReductionDb(void * class_handler);
extern void SuperpoweredLimiter_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif