// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDWHOOSH__
#define __AUTO_CODE_SUPERPOWEREDWHOOSH__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredWhoosh_enable(void * class_handler,bool flag);
extern void SuperpoweredWhoosh_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredWhoosh_reset(void * class_handler);
extern int SuperpoweredWhoosh_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredWhoosh_delete(void * class_handler);
extern void SuperpoweredWhoosh_setFrequency(void * class_handler,float hz);
extern void * SuperpoweredWhoosh_new(unsigned int samplerate);

#ifdef __cplusplus
}
#endif

#endif