// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDREVERB__
#define __AUTO_CODE_SUPERPOWEREDREVERB__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredReverb_reset(void * class_handler);
extern void SuperpoweredReverb_setWidth(void * class_handler,float value);
extern void SuperpoweredReverb_setLowCut(void * class_handler,float hz);
extern void SuperpoweredReverb_setMix(void * class_handler,float value);
extern void SuperpoweredReverb_setPredelay(void * class_handler,float ms);
extern void SuperpoweredReverb_setWet(void * class_handler,float value);
extern void SuperpoweredReverb_enable(void * class_handler,bool flag);
extern void SuperpoweredReverb_setDry(void * class_handler,float value);
extern void SuperpoweredReverb_setRoomSize(void * class_handler,float value);
extern int SuperpoweredReverb_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredReverb_setDamp(void * class_handler,float value);
extern void * SuperpoweredReverb_new(unsigned int samplerate, unsigned int maximumSamplerate);
extern void SuperpoweredReverb_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredReverb_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif