// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDCPU__
#define __AUTO_CODE_SUPERPOWEREDCPU__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredCPU_setSustainedPerformanceMode(bool enable);

#ifdef __cplusplus
}
#endif

#endif