// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDBANDPASSFILTERBANK__
#define __AUTO_CODE_SUPERPOWEREDBANDPASSFILTERBANK__

#ifdef __cplusplus
extern "C" {
#endif

extern void * SuperpoweredBandpassFilterbank_new(int numBands, float* frequencies, float* widths, unsigned int samplerate);
extern void SuperpoweredBandpassFilterbank_process(void * class_handler,float* input, float* bands, float* peak, float* sum, unsigned int numberOfSamples, int group);
extern void * SuperpoweredBandpassFilterbank_new(int numGroups, int numBandsInGroup, float* frequencies, float* widths, unsigned int samplerate);
extern void SuperpoweredBandpassFilterbank_delete(void * class_handler);
extern void SuperpoweredBandpassFilterbank_processNoAdd(void * class_handler,float* input, float* bands, float* peak, float* sum, unsigned int numberOfSamples, int group);
extern void SuperpoweredBandpassFilterbank_setSamplerate(void * class_handler,unsigned int samplerate);

#ifdef __cplusplus
}
#endif

#endif