// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDDECODER__
#define __AUTO_CODE_SUPERPOWEREDDECODER__

#ifdef __cplusplus
extern "C" {
#endif

extern unsigned char mp3File_decode(void * class_handler,short* pcmOutput, unsigned int* samples);

extern unsigned char waveFile_decode(void * class_handler,short* pcmOutput, unsigned int* samples);

extern unsigned char aacFile_decode(void * class_handler,short* pcmOutput, unsigned int* samples);

extern unsigned char SuperpoweredDecoder_getAudioStartSample(void * class_handler,unsigned int* startSample, unsigned int limitSamples, int decibel, unsigned int* cancelIfBuffering);
extern unsigned char SuperpoweredDecoder_seek(void * class_handler,long long sample, bool precise);
extern void SuperpoweredDecoder_reconnectToMediaserver(void * class_handler);
extern void * SuperpoweredDecoder_new(void * downloadedCallback, void* clientData);
extern void SuperpoweredDecoder_getMetaData(void * class_handler,char** artist, char** title, char** album, void** image, int* imageSizeBytes, float* bpm,void * callback, void* clientData, int maxFrameDataSize);
extern unsigned char SuperpoweredDecoder_decode(void * class_handler,short* pcmOutput, unsigned int* samples);
extern const char * SuperpoweredDecoder_open(void * class_handler,char const* path, bool metaOnly, int offset, int length, int stemsIndex, char** customHTTPHeaders, int* errorCode);
extern void SuperpoweredDecoder_delete(void * class_handler);
extern int SuperpoweredDecoder_getStemsInfo(void * class_handler,char** names, char** colors, stemsCompressor* compressor, stemsLimiter* limiter);

extern unsigned char aiffFile_decode(void * class_handler,short* pcmOutput, unsigned int* samples);

#ifdef __cplusplus
}
#endif

#endif