// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDFLANGER__
#define __AUTO_CODE_SUPERPOWEREDFLANGER__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredFlanger_enable(void * class_handler,bool flag);
extern void SuperpoweredFlanger_setWet(void * class_handler,float value);
extern int SuperpoweredFlanger_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples);
extern void SuperpoweredFlanger_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredFlanger_setLFOBeats(void * class_handler,float beats);
extern void SuperpoweredFlanger_reset(void * class_handler);
extern void * SuperpoweredFlanger_new(unsigned int samplerate);
extern void SuperpoweredFlanger_setDepth(void * class_handler,float value);
extern void SuperpoweredFlanger_delete(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif