// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#ifndef __AUTO_CODE_SUPERPOWEREDECHO__
#define __AUTO_CODE_SUPERPOWEREDECHO__

#ifdef __cplusplus
extern "C" {
#endif

extern void SuperpoweredEcho_enable(void * class_handler,bool flag);
extern void SuperpoweredEcho_setMix(void * class_handler,float mix);
extern void SuperpoweredEcho_reset(void * class_handler);
extern void * SuperpoweredEcho_new(unsigned int samplerate, unsigned int maximumSamplerate);
extern void SuperpoweredEcho_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredEcho_delete(void * class_handler);
extern int SuperpoweredEcho_process(void * class_handler,float* input, float* output, unsigned int numberOfFrames);
extern int SuperpoweredEcho_process(void * class_handler,float* input, float* output, unsigned int numberOfFrames, SuperpoweredFX* fx);

extern int SuperpoweredDelay_process(void * class_handler,float* input, int output, SuperpoweredFX* numberOfFrames);
extern void SuperpoweredDelay_setSamplerate(void * class_handler,unsigned int samplerate);
extern void SuperpoweredDelay_reset(void * class_handler);

#ifdef __cplusplus
}
#endif

#endif