// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredDelay.h"
#include "CLANG_SuperpoweredDelay.h"
void * SuperpoweredDelay_new(unsigned int maximumDelayMs, unsigned int maximumSamplerate, unsigned int maximumNumberOfFramesToProcess, unsigned int samplerate)
{
  return (void*)(new SuperpoweredDelay(maximumDelayMs,maximumSamplerate,maximumNumberOfFramesToProcess,samplerate));
}

const float * const SuperpoweredDelay_process(void * class_handler,float* input, int numberOfFrames, SuperpoweredFX* fx)
{
  SuperpoweredDelay * real_class_handler = (SuperpoweredDelay *)class_handler;
  return real_class_handler->process(input,numberOfFrames,fx);
}

void SuperpoweredDelay_reset(void * class_handler)
{
  SuperpoweredDelay * real_class_handler = (SuperpoweredDelay *)class_handler;
  return real_class_handler->reset();
}

void SuperpoweredDelay_delete(void * class_handler)
{
  delete (SuperpoweredDelay *)class_handler;
}

void SuperpoweredDelay_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredDelay * real_class_handler = (SuperpoweredDelay *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}