// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredClipper.h"
#include "CLANG_SuperpoweredClipper.h"
void * SuperpoweredClipper_new()
{
  return (void*)(new SuperpoweredClipper());
}

void SuperpoweredClipper_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples)
{
  SuperpoweredClipper * real_class_handler = (SuperpoweredClipper *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples);
}

void SuperpoweredClipper_delete(void * class_handler)
{
  delete (SuperpoweredClipper *)class_handler;
}