// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredMixer.h"
#include "CLANG_SuperpoweredMixer.h"
void SuperpoweredStereoMixer_processPFL(void * class_handler,float** channels, float** outputs, bool* channelSwitches[4], float* channelOutputLevels[4], unsigned int numberOfSamples)
{
  SuperpoweredStereoMixer * real_class_handler = (SuperpoweredStereoMixer *)class_handler;
  return real_class_handler->processPFL(channels,outputs,channelSwitches[4],channelOutputLevels[4],numberOfSamples);
}

void SuperpoweredStereoMixer_process(void * class_handler,float** inputs, float** outputs, float* inputLevels[8], float* outputLevels[2], float* inputMeters[8], float* outputMeters[2], unsigned int numberOfSamples)
{
  SuperpoweredStereoMixer * real_class_handler = (SuperpoweredStereoMixer *)class_handler;
  return real_class_handler->process(inputs,outputs,inputLevels[8],outputLevels[2],inputMeters[8],outputMeters[2],numberOfSamples);
}

void * SuperpoweredStereoMixer_new()
{
  return (void*)(new SuperpoweredStereoMixer());
}

void SuperpoweredStereoMixer_delete(void * class_handler)
{
  delete (SuperpoweredStereoMixer *)class_handler;
}

void SuperpoweredMonoMixer_delete(void * class_handler)
{
  delete (SuperpoweredMonoMixer *)class_handler;
}

void SuperpoweredMonoMixer_process(void * class_handler,float** inputs, void* output, float* inputLevels, float outputGain, unsigned int numberOfSamples)
{
  SuperpoweredMonoMixer * real_class_handler = (SuperpoweredMonoMixer *)class_handler;
  return real_class_handler->process(inputs,output,inputLevels,outputGain,numberOfSamples);
}

void * SuperpoweredMonoMixer_new()
{
  return (void*)(new SuperpoweredMonoMixer());
}