// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredResampler.h"
#include "CLANG_SuperpoweredResampler.h"
void SuperpoweredResampler_reset(void * class_handler)
{
  SuperpoweredResampler * real_class_handler = (SuperpoweredResampler *)class_handler;
  return real_class_handler->reset();
}

void * SuperpoweredResampler_new()
{
  return (void*)(new SuperpoweredResampler());
}

int SuperpoweredResampler_process(void * class_handler,short* input, float* temp, short* output, int numberOfSamples, bool reverse, bool highQuality, float rateAdd)
{
  SuperpoweredResampler * real_class_handler = (SuperpoweredResampler *)class_handler;
  return real_class_handler->process(input,temp,output,numberOfSamples,reverse,highQuality,rateAdd);
}

int SuperpoweredResampler_process(void * class_handler,short* input, float* output, int numberOfSamples, bool reverse, bool highQuality, float rateAdd)
{
  SuperpoweredResampler * real_class_handler = (SuperpoweredResampler *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples,reverse,highQuality,rateAdd);
}

void SuperpoweredResampler_delete(void * class_handler)
{
  delete (SuperpoweredResampler *)class_handler;
}