// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredGate.h"
#include "CLANG_SuperpoweredGate.h"
void SuperpoweredGate_enable(void * class_handler,bool flag)
{
  SuperpoweredGate * real_class_handler = (SuperpoweredGate *)class_handler;
  return real_class_handler->enable(flag);
}

void SuperpoweredGate_delete(void * class_handler)
{
  delete (SuperpoweredGate *)class_handler;
}

void * SuperpoweredGate_new(unsigned int samplerate)
{
  return (void*)(new SuperpoweredGate(samplerate));
}

void SuperpoweredGate_reset(void * class_handler)
{
  SuperpoweredGate * real_class_handler = (SuperpoweredGate *)class_handler;
  return real_class_handler->reset();
}

int SuperpoweredGate_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples)
{
  SuperpoweredGate * real_class_handler = (SuperpoweredGate *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples);
}

void SuperpoweredGate_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredGate * real_class_handler = (SuperpoweredGate *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}