// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredRecorder.h"
#include "CLANG_SuperpoweredRecorder.h"
void SuperpoweredRecorder_delete(void * class_handler)
{
  delete (SuperpoweredRecorder *)class_handler;
}

int SuperpoweredRecorder_start(void * class_handler,char const* destinationPath)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->start(destinationPath);
}

void * SuperpoweredRecorder_new(char const* tempPath, unsigned int samplerate, unsigned int minSeconds, unsigned char numChannels, bool applyFade,void * callback,void * clientData)
{
  return (void*)(new SuperpoweredRecorder(tempPath,samplerate,minSeconds,numChannels,applyFade,callback,clientData));
}

void SuperpoweredRecorder_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}

void SuperpoweredRecorder_addToTracklist(void * class_handler,char* artist, char* title, int offsetSeconds, bool takeOwnership)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->addToTracklist(artist,title,offsetSeconds,takeOwnership);
}

void SuperpoweredRecorder_stop(void * class_handler)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->stop();
}

unsigned int SuperpoweredRecorder_process(void * class_handler,float* input, unsigned int numberOfSamples)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->process(input,numberOfSamples);
}

unsigned int SuperpoweredRecorder_process(void * class_handler,float* input0, float* input1, unsigned int numberOfSamples)
{
  SuperpoweredRecorder * real_class_handler = (SuperpoweredRecorder *)class_handler;
  return real_class_handler->process(input0,input1,numberOfSamples);
}