// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredFlanger.h"
#include "CLANG_SuperpoweredFlanger.h"
void SuperpoweredFlanger_enable(void * class_handler,bool flag)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->enable(flag);
}

void SuperpoweredFlanger_setWet(void * class_handler,float value)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->setWet(value);
}

int SuperpoweredFlanger_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples);
}

void SuperpoweredFlanger_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}

void SuperpoweredFlanger_setLFOBeats(void * class_handler,float beats)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->setLFOBeats(beats);
}

void SuperpoweredFlanger_reset(void * class_handler)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->reset();
}

void * SuperpoweredFlanger_new(unsigned int samplerate)
{
  return (void*)(new SuperpoweredFlanger(samplerate));
}

void SuperpoweredFlanger_setDepth(void * class_handler,float value)
{
  SuperpoweredFlanger * real_class_handler = (SuperpoweredFlanger *)class_handler;
  return real_class_handler->setDepth(value);
}

void SuperpoweredFlanger_delete(void * class_handler)
{
  delete (SuperpoweredFlanger *)class_handler;
}