// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredLimiter.h"
#include "CLANG_SuperpoweredLimiter.h"
void SuperpoweredLimiter_enable(void * class_handler,bool flag)
{
  SuperpoweredLimiter * real_class_handler = (SuperpoweredLimiter *)class_handler;
  return real_class_handler->enable(flag);
}

void SuperpoweredLimiter_reset(void * class_handler)
{
  SuperpoweredLimiter * real_class_handler = (SuperpoweredLimiter *)class_handler;
  return real_class_handler->reset();
}

int SuperpoweredLimiter_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples)
{
  SuperpoweredLimiter * real_class_handler = (SuperpoweredLimiter *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples);
}

void * SuperpoweredLimiter_new(unsigned int samplerate)
{
  return (void*)(new SuperpoweredLimiter(samplerate));
}

void SuperpoweredLimiter_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredLimiter * real_class_handler = (SuperpoweredLimiter *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}

float SuperpoweredLimiter_getGainReductionDb(void * class_handler)
{
  SuperpoweredLimiter * real_class_handler = (SuperpoweredLimiter *)class_handler;
  return real_class_handler->getGainReductionDb();
}

void SuperpoweredLimiter_delete(void * class_handler)
{
  delete (SuperpoweredLimiter *)class_handler;
}