// CPP to C glue code generated by Sweaty on Wed Jun 13 23:03:10 2018

// NO WARRANTIES ON PRODUCTION, for experiemental purposes only.
// TODO: Class member variable *MUST* be added manually
#include "/usr/local/Superpowered/SuperpoweredRoll.h"
#include "CLANG_SuperpoweredRoll.h"
void SuperpoweredRoll_reset(void * class_handler)
{
  SuperpoweredRoll * real_class_handler = (SuperpoweredRoll *)class_handler;
  return real_class_handler->reset();
}

void SuperpoweredRoll_setSamplerate(void * class_handler,unsigned int samplerate)
{
  SuperpoweredRoll * real_class_handler = (SuperpoweredRoll *)class_handler;
  return real_class_handler->setSamplerate(samplerate);
}

void * SuperpoweredRoll_new(unsigned int samplerate)
{
  return (void*)(new SuperpoweredRoll(samplerate));
}

void SuperpoweredRoll_delete(void * class_handler)
{
  delete (SuperpoweredRoll *)class_handler;
}

int SuperpoweredRoll_process(void * class_handler,float* input, float* output, unsigned int numberOfSamples)
{
  SuperpoweredRoll * real_class_handler = (SuperpoweredRoll *)class_handler;
  return real_class_handler->process(input,output,numberOfSamples);
}

void SuperpoweredRoll_enable(void * class_handler,bool flag)
{
  SuperpoweredRoll * real_class_handler = (SuperpoweredRoll *)class_handler;
  return real_class_handler->enable(flag);
}